
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";


export const USER_SAVE_FAIL = "USER_SAVE_FAIL";
export const USER_SAVE_SUCCESS = "USER_SAVE_SUCCESS";

export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";


export const TASKS_LOAD_FAIL = "TASKS_LOAD_FAIL";
export const TASKS_LOAD_SUCCESS = "TASKS_LOAD_SUCCESS";

export const TASKS_DELETE_FAIL = "TASKS_DELETE_FAIL";
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS";

export const TASKS_UPDATE_FAIL = "TASKS_UPDATE_FAIL";
export const TASKS_UPDATE_SUCCESS = "TASKS_UPDATE_SUCCESS";



export const TASKS_SAVE_FAIL = "TASKS_SAVE_FAIL";
export const TASKS_SAVE_SUCCESS = "TASKS_SAVE_SUCCESS";



export const BUSINESS_DATA_LOAD_FAIL = "BUSINESS_DATA_LOAD_FAIL";
export const BUSINESS_DATA_LOAD_SUCCESS = "BUSINESS_DATA_LOAD_SUCCESS";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";